.github/actions/spelling/allow.txt, CODE_OF_CONDUCT.md, src/a2a/server/tasks/inmemory_task_store.py, src/a2a/types.py, src/a2a/utils/errors.py, src/a2a/utils/helpers.py, tests/server/tasks/test_inmemory_task_store.py, tests/server/tasks/test_task_manager.py
Hi,
This PR fixes typos in various files.
Best regards,
Didier
- [X ] Follow the [`CONTRIBUTING` Guide](https://github.com/google/a2a-python/blob/main/CONTRIBUTING.md).
- [X ] Make your Pull Request title in the <https://www.conventionalcommits.org/> specification.
=> fix: correcting typos in various files

src/a2a/server/request_handlers/default_request_handler.py
During streaming, a queue is setup with a default task_id. If an agent returns task objects with the same task_id, we will reuse the default queue.
If a new task_id is returned from the agent, we will log this as warning and create a new queue for the provided task object.
=> fix: Handle reusing queue on task events

.github/actions/spelling/excludes.txt, .github/linters/.mypy.ini, .github/workflows/linter.yaml, .github/workflows/python-publish.yml, examples/google_adk/birthday_planner/adk_agent_executor.py, examples/google_adk/calendar_agent/adk_agent_executor.py, noxfile.py, pyproject.toml, src/a2a/server/agent_execution/context.py, src/a2a/server/request_handlers/default_request_handler.py, src/a2a/server/tasks/task_updater.py, src/a2a/utils/__init__.py, src/a2a/utils/artifact.py, src/a2a/utils/message.py, src/a2a/utils/task.py, tests/utils/test_helpers.py, tests/utils/test_telemetry.py
- Re-enable linting on PR
- Disable linting on `examples/` directory
- Add `no_implicit_optional` to noxfile.py
- Exclude all of `.github/workflows/` from spell check
- Ran formatting
=> ci: Fix Linting/Formatting issues

examples/google_adk/birthday_planner/__main__.py, examples/google_adk/calendar_agent/__main__.py, examples/google_adk/calendar_agent/adk_agent.py, examples/helloworld/__main__.py, examples/langgraph/__main__.py, examples/langgraph/agent_executor.py, examples/langgraph/test_client.py
=> fix: MYPY fixes on Langraph example

.gitignore, development.md, examples/helloworld/test_client.py, examples/langgraph/test_client.py, src/a2a/server/request_handlers/default_request_handler.py, src/a2a/types.py, tests/client/test_client.py, tests/server/events/test_event_consumer.py, tests/server/events/test_event_queue.py, tests/server/request_handlers/test_jsonrpc_handler.py, tests/server/tasks/test_inmemory_task_store.py, tests/server/tasks/test_task_manager.py, tests/test_types.py
=> fix: Rename type to kind

.github/actions/spelling/allow.txt, README.md
=> chore: update readme

examples/helloworld/__main__.py
The `helloworld` example do not act as stream enable, so I get exception
```
object async_generator can't be used in 'await' expression
```
when I try to invoke `client.send_message_streaming`
=> fix: disable stream for helloworld example, since it do not support

tests/server/events/test_inmemory_queue_manager.py
Hi,
adding 12 tests for InMemoryQueueManager. They all pass: see execution report below
Didier
```
============================= test session starts ==============================
collecting ... collected 12 items
server/events/test_inmemory_queue_manager.py::TestInMemoryQueueManager::test_init PASSED [  8%]
server/events/test_inmemory_queue_manager.py::TestInMemoryQueueManager::test_add_new_queue PASSED [ 16%]
server/events/test_inmemory_queue_manager.py::TestInMemoryQueueManager::test_add_existing_queue PASSED [ 25%]
server/events/test_inmemory_queue_manager.py::TestInMemoryQueueManager::test_get_existing_queue PASSED [ 33%]
server/events/test_inmemory_queue_manager.py::TestInMemoryQueueManager::test_get_nonexistent_queue PASSED [ 41%] …
```
=> test: adding 12 tests for InMemoryQueueManager

.github/actions/spelling/allow.txt, .github/release-please.yml, .github/workflows/update-a2a-types.yml, CHANGELOG.md, development.md
- Runs daily at Midnight UTC
- https://github.com/google/A2A/blob/main/specification/json/a2a.json
=> ci: Create GitHub Action to generate `types.py` from specification JSON

tests/server/request_handlers/test_jsonrpc_handler.py, tests/server/test_integration.py
=> test: Adding 8 tests for jsonrpc_handler.py and also fix minor waring in test_integration.py

.github/workflows/update-a2a-types.yml
Followup to https://github.com/google/A2A/pull/634
=> ci: Change update-a2a-types to use repository_dispatch

pyproject.toml, src/a2a/server/events/event_consumer.py
There was a race condition based on when the generator yielded with respect to when the queue was closed.
=> Fix: fix hello world example for python 3.12

src/a2a/utils/message.py
This pull request adds two optional parameters - `final` and `metadata` - to the utility functions `new_agent_text_message` and `new_agent_parts_message`:
* **`final`** (`bool | None`): Indicates whether the message is the final one. Useful for managing control flow in streaming agent interactions.
* **`metadata`** (`dict[str, Any] | None`): Allows attaching additional information to a message, such as token counts, response time, or other relevant metrics, which is helpful for monitoring and debugging during development.
**NOTE:** These parameters were already documented but had not been included in the function signatures. This PR ensures that the implementation is aligned with the documentation and supports enhanced message handling for streaming agents.
---
=> docs: remove final and metadata fields from docstring

.github/workflows/update-a2a-types.yml
- Followup to https://github.com/google-a2a/A2A/pull/692
=> ci: Change `update-a2a-types.yml` to use Commit Message for PR Title

src/a2a/server/apps/starlette_app.py, src/a2a/utils/helpers.py
=> fix: remove unnecessary hasattr checks

src/a2a/server/events/event_queue.py, src/a2a/server/tasks/task_updater.py, tests/server/events/test_event_queue.py, tests/server/request_handlers/test_default_request_handler.py, tests/server/tasks/test_task_updater.py
Fixes #111 🦕
> [!WARNING]  
> Backwards incompatible change, as `EventQueue.enqueue_event()` becomes async.
The implementation of the `AgentExecutor` usually looks like this:
```
class SomeAgentExecutor(AgentExecutor):
async def execute(self, context: RequestContext, event_queue: EventQueue) -> None:
task_updater = TaskUpdater(event_queue, context.task_id, context.context_id)
task_updater.start_work()
async for event in self._run_async(...):
if event.is_final_response():
task_updater.add_artifact(parts)
task_updater.complete()
break
task_updater.update_status(
TaskState.working,
message=task_updater.new_agent_message(parts),
)
```
The issue is that the loop inside `execute()` calls `task_updater.update_status()` synchronously.
If `update_status` is not an async function, then the …
=> fix(stream): don't block event loop in EventQueue

.github/PULL_REQUEST_TEMPLATE.md
=> fix: Fix Release Version

src/a2a/server/events/event_consumer.py, tests/server/events/test_event_consumer.py
Event consumer currently only stops properly for streaming events. But for sync calls that transition to input_required state, the consumer doesn't treat them as final events and results in queue closed exception.
Example test:
```py
task: Task= new_task(context.message)
result = await self.agent.invoke()
message = new_agent_text_message(result)
task.status = TaskStatus(state=TaskState.input_required, message=message)
event_queue.enqueue_event(task)
```
=> fix: Event consumer should stop on input_required

scripts/grpc_gen_post_processor.py
=> chore: Post processor script for grpc generation.

src/a2a/server/apps/jsonrpc/jsonrpc_app.py
This PR enhances our A2A framework by adding HTTP headers to the `ServerCallContext`, making them accessible via `context.state['headers']`. The call context is a key component of our request-handling system, designed to provide handlers with request-specific information—like user details and additional state—in a structured, modular way. This abstraction keeps our handlers clean and decoupled from the raw HTTP request.
**Why Add Headers to the Context?**
*   **Essential Metadata:** HTTP headers carry critical information, such as authentication tokens, content types, and custom parameters, that handlers often need to process requests correctly. Including headers in the context ensures this data is easily accessible.
*   **Architectural Consistency:** We already use the call context to …
=> feat: Add HTTP Headers to ServerCallContext for Improved Handler Access

scripts/grpc_gen_post_processor.py, src/a2a/server/events/event_consumer.py, src/a2a/server/request_handlers/grpc_handler.py, uv.lock
It seemed that some files were not properly formatted by `nox -s format`, so I manually ran the formatting steps defined in `noxfile.py`:
- `uv run no_implicit_optional --use-union-or .`  
- `uv run ruff check --fix-only --config .github/linters/.ruff.toml .`  
- `uv run ruff …
=> style: format code using ruff fix and format

src/a2a/server/request_handlers/grpc_handler.py
Fix references in `a2a/server/request_handlers/grpc_handler.py` to `grpc.aio.ServicerContext`. The import for `grpc.aio` was missing and various functions incorrectly referenced `grpc.ServicerContext`.
This is a backwards compatible change, it's just typing annotations for internal functions that were off. The actual code itself worked, as can be demonstrated by running the sample agent in `a2aproject/a2a-samples/samples/python/agents/dice_agent_grpc`.
=> fix: Fix reference to `grpc.aio.ServicerContext`

CONTRIBUTING.md
=> chore(docs): Remove Google references from contributing guide

src/a2a/server/tasks/task_updater.py, tests/server/tasks/test_task_updater.py
This PR adds a lock to the `TaskUpdater` to prevent race conditions when updating tasks that are in a terminal state (e.g., completed, failed). This ensures updates are handled atomically, making task state management more robust.
* `src/a2a/server/tasks/task_updater.py`
* `tests/server/tasks/test_task_updater.py`
* **Robustness**: Prevents race conditions during concurrent task updates.
* **Stability**: Ensures reliable task execution in production.
* **Test Coverage**: Adds new tests for concurrent scenarios.
- `fix:` which represents bug fixes, and correlates to a …
=> feat(server): Add lock to TaskUpdater to prevent race conditions

src/a2a/server/apps/jsonrpc/jsonrpc_app.py
- Resolve JSCPD errors
- initializers from subclass should automatically call the initializer of the superclass, explicitly listing them shouldn't be needed.
=> refactor: Add missing parameters from `JSONRPCApplication.build()`

src/a2a/server/request_handlers/default_request_handler.py, tests/server/request_handlers/test_default_request_handler.py
Push notifications are not being triggered for message/send operations without an initial task.
=> fix: Send push notifications for message/send

src/a2a/server/agent_execution/context.py, tests/server/agent_execution/test_context.py
- [ x ] Follow the [`CONTRIBUTING` Guide](https://github.com/a2aproject/a2a-python/blob/main/CONTRIBUTING.md).
- [ x ] Make your Pull Request title in the <https://www.conventionalcommits.org/> specification.
- [ x ] Ensure the tests and linter pass (Run `nox -s format` from the …
=> feat: add metadata property to RequestContext

src/a2a/client/__init__.py, src/a2a/client/client.py, src/a2a/client/errors.py, tests/client/test_client.py
=> fix: Handle readtimeout errors.

src/a2a/utils/task.py, tests/utils/test_task.py
This update addresses an issue where the `completed_task` function in `a2a/utils/task.py` did not perform any validation on the `artifacts` list. This could lead to unexpected behavior if an empty or invalid list was provided.
This change introduces a validation check to ensure that the `artifacts` list is a non-empty list of `Artifact` objects, raising a `ValueError` if the validation fails.
**Changes:**
- Modified `a2a/utils/task.py` to add a validation check for the `artifacts` parameter in the `completed_task` function.
- Updated `tests/utils/test_task.py` to include tests for the new validation logic, covering cases with empty lists and lists containing invalid items.
=> fix: Add validation for empty artifact lists in `completed_task`

src/a2a/server/tasks/task_manager.py, tests/server/tasks/test_task_manager.py
Previously, the `TaskManager` class in `a2a/server/tasks/task_manager.py` did not perform any validation on the `task_id` during initialization. This could lead to silent failures or inconsistencies in task storage if an invalid ID (such as an empty string) was provided.
Adding this validation improves the robustness of the `TaskManager` and prevents downstream errors in task management, especially for database or in-memory stores.
In `a2a/server/tasks/task_manager.py`, a check has been added to the `__init__` method of the `TaskManager` to validate the `task_id`. It now ensures that if a `task_id` is provided, it is a non-empty string. If the validation fails, a `ValueError` is raised.
A corresponding unit test has been added to `tests/server/tasks/test_task_manager.py` to verify that …
=> fix: Add Input Validation for Task IDs in TaskManager

src/a2a/utils/task.py, tests/utils/test_task.py
Adding input validation to the `new_task` function in `a2a/utils/task.py`. The new validation checks if any `part` within a `Message` contains empty content (e.g., `TextPart(text='')`) and raises a `ValueError` if it does.
This enhancement improves the system's reliability by preventing the creation and processing of tasks with invalid or incomplete message data.
- Updated the `new_task` function in `src/a2a/utils/task.py` to iterate through message parts and check for empty content.
- Added a new test case, `test_new_task_invalid_message_empty_content`, in `tests/utils/test_task.py` to ensure the validation works as expected.
=> fix: Add Input Validation for Empty Message Content

src/a2a/_base.py, tests/test_types.py
=> fix: Remove `DeprecationWarning` for regular properties

src/a2a/server/agent_execution/context.py
Standardizes property null check patterns across the codebase by converting early return style to ternary operator style for consistency.
- **RequestContext.configuration**: Converted from `if not self._params: return None` pattern to ternary operator
- **RequestContext.metadata**: Converted from `if not self._params: return {}` pattern to ternary operator
---
- `feat!:`, or `fix!:`, `refactor!:`, etc., which …
=> style: standardize property null checks to use ternary operators

src/a2a/server/tasks/task_updater.py
=> feat: Add `metadata` as parameter to `TaskUpdater.update_status()`

pyproject.toml
We want to use this in a project that requires `protobuf==6.31.1`. Version history indicates upgrading a2a-python to that version is not possible at the moment. Therefore, relax the required version to just be `>=5.29.5` (instead of `==`).
This does print a warning when using a2a-python with a (major) newer version, but my tests show that it works just fine. Better to live with the warning than not being able to use a2a-python at all.
This does not update the buf generation config as this would upgrade to newer proto requirements (and generate protos for newer versions).
=> fix: relax protobuf dependency version requirement

src/a2a/client/transports/grpc.py, tests/client/test_grpc_client.py
Using `response.task` will reset the oneof field if the `msg` field was set. Properly check return value.
=> fix: Use HasField for simple message retrieval for grpc transport

src/a2a/utils/proto_utils.py, tests/utils/test_proto_utils.py
Fixes the issue when using protoutils, mime type and file name are lost
=> fix: Add missing mime_type and name in proto conversion utils

src/a2a/server/tasks/task_updater.py
=> feat: Add extensions support to `TaskUpdater.add_artifact`

src/a2a/server/apps/rest/rest_adapter.py, src/a2a/server/request_handlers/jsonrpc_handler.py, tests/server/request_handlers/test_jsonrpc_handler.py
=> fix: Sync jsonrpc and rest implementation of authenticated agent card

src/a2a/server/apps/jsonrpc/jsonrpc_app.py, tests/server/apps/jsonrpc/test_jsonrpc_app.py
SDK users sometimes need to know which JSON-RPC method is being processed to adjust their implementation, e.g.:
* If the method is `message/send`, they may want to use `invoke()`/`run()` when calling their LLM API, and `stream()`/`run_streamed()` for `message/stream`. 
Added a `method` field to `ServerCallContext.state`, similar to `headers`.
Added a small test to ensure that method parsing is correct.
Fixes #451
=> feat: add JSON-RPC `method` to `ServerCallContext.state`

src/a2a/client/transports/rest.py, src/a2a/server/events/event_queue.py, src/a2a/server/request_handlers/default_request_handler.py, tests/server/events/test_event_queue.py, tests/server/request_handlers/test_default_request_handler.py
It's been described well in #464 :
> When the client-side connection is terminated, the EventConsumer stops processing. As a result, any changes to the task state after the disconnection are not persisted to the TaskStore. The task itself continues running in the background, but its updated state is no longer reflected in the TaskStore.
This has been addressed in this PR by simply adding a catch for `(asyncio.CancelledError, GeneratorExit)` in the `on_message_send_stream` method. 
However, adding that revealed a difference in semantics between Python 3.13+ and <3.13 for `EventQueue.close()`. I have also addressed that. 
[@azyobuzin](https://github.com/azyobuzin) provided a detailed guide on this in #464 . My only addition would be to add loggers for `a2a.server.events.event_queue` and …
=> fix: Task state is not persisted to task store after client disconnect

README.md
MacOS doesn't support commands like `pip install package[extra]` without escaping. Other installation commands are written like `pip install "a2a-sdk[extra]"`, for this reason. I have just fixed this issue.
=> docs: `a2a-sdk[all]` installation command in Readme

src/a2a/utils/errors.py
Add `__str__` and `__repr__` methods to `ServerError` and fix the misleading comment in the constructor
=> fix: Add `__str__` and `__repr__` methods to `ServerError`
