a2aproject/a2a-python

examples/helloworld/__main__.py
src/a2a/server/agent_execution/context.py
src/a2a/server/events/in_memory_queue_manager.py

fix: Fix mypy errors and enable streaming for hw example

---

README.md

docs: fix CONTRIBUTING.md link

---

pyproject.toml
uv.lock

ci: Setup repo for publishing

---

src/a2a/server/agent_execution/context.py
src/a2a/server/tasks/task_updater.py
src/a2a/utils/__init__.py
src/a2a/utils/artifact.py
src/a2a/utils/helpers.py
src/a2a/utils/message.py
src/a2a/utils/task.py

feat: Updates to helper methods to improve developer quality of life

---

.ruff.toml
examples/google_adk/birthday_planner/README.md
examples/google_adk/calendar_agent/README.md

fix: Update Required Python Version to 3.13 in all tutorials

---

src/a2a/types.py

Just running the type generation code.

chore: Update generated types after google/A2A#594

---

examples/helloworld/__main__.py

Revert "fix: disable stream for helloworld example, since it do not support"

---

buf.gen.yaml

fix: update generation output path to src/a2a/grpc

---

src/a2a/utils/proto_utils.py

fix: update regex references for pushNotificationConfigs

---

.pre-commit-config.yaml

- Add uv.lock generation
- Add commitzen for conventionalcommits
- Add gitleaks
- Ran auto-update

chore: Updates to pre-commit hook

---

tests/server/tasks/test_result_aggregator.py

test: Ensure asyncio tasks are created correctly in tests

---

.vscode/extensions.json

- add `.vscode/extensions.json` file to recommend vscode extensions for this workspace
- add [`charliermarsh.ruff`](https://marketplace.visualstudio.com/items?itemName=charliermarsh.ruff) extension

chore: add `.vscode/extensions.json` to recommend vscode extensions for this workspace

---

src/a2a/utils/telemetry.py

fix: Handle asyncio.cancellederror and raise to propagate back

---

src/a2a/server/tasks/__init__.py

fix: Resolve dependency issue with sql stores

---

src/a2a/client/auth/interceptor.py
tests/client/test_auth_middleware.py

Refactored `tests/client/test_auth_middleware.py` and added test cases to improve coverage for `credentials.py` and `interceptor.py`.
- `src/a2a/client/auth/credentials.py`: 94% -> 100%
- `src/a2a/client/auth/interceptor.py`: 71% -> 94%
Fixes N/A 🦕

test: improve test coverage

---

tests/server/request_handlers/test_default_request_handler.py

chore: fix task for no_existing_task scenario

---

src/a2a/utils/__init__.py
src/a2a/utils/message.py
tests/utils/test_message.py

feat: Add `get_data_parts()` and `get_file_parts()` helper methods

---

src/a2a/client/__init__.py
src/a2a/client/grpc_client.py
src/a2a/server/request_handlers/__init__.py

fix: Prevent import grpc issues for Client after making dependencies optional

---

.github/actions/spelling/allow.txt
.github/workflows/conventional-commits.yml

Google GitHub App will be deprecated

ci: Add Conventional Commits GitHub Action

---

src/a2a/server/apps/jsonrpc/jsonrpc_app.py
src/a2a/server/apps/rest/rest_adapter.py

fix: Remove logger error from init on `rest_adapter` and `jsonrpc_app`

---

src/a2a/utils/proto_utils.py

fix(grpc): Fix missing extensions from protobuf
